### ISSUE TITLE
Received emails do not get transformed to tickets

### ISSUE THREAD

**Issue by fracalo** [scott/helpy_imap#1]
For some reasons ( I'm not a Ruby expert so I might be missing something obvious ) when `helpy:mailman` tries to process a mail I get the following error:

`#<TypeError: no implicit conversion of Symbol into Integer>`

following all the output:
```
$ RAILS_ENV=production rake  helpy:mailman                                                      
I, [2018-12-06T11:12:58.807509 #21696]  INFO -- : Mailman v0.7.3 started
I, [2018-12-06T11:12:58.807609 #21696]  INFO -- : IMAP receiver enabled (helpdesk2@ssd.it@mailserver.ssd.it).
I, [2018-12-06T11:12:58.827376 #21696]  INFO -- : Polling disabled. Checking for messages once.
I, [2018-12-06T11:12:59.469204 #21696]  INFO -- : Got new message from 'zerostress@asdf.it' with subject 'sdfg'.
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /usr/local/rvm/gems/ruby-2.3.3@helpy/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
#<TypeError: no implicit conversion of Symbol into Integer>
```
it fails the require method so i guess it's having problems loading the module,
if you could shed some light I would appreciate.

**Comment by benoitgoyette** [comment]
I get the same error when the email has a CC

in imap_processor.rb, at line 26
```
cc = @email.cc ? @email.cc.map { |e| e[:full] }.join(", ") : nil
```
@email.cc is an array of strings, not Hash, so `e[:full]` crashes with the error  `no implicit conversion of Symbol into Integer`

**Comment by fracalo** [comment]
In my case the error was on the [`get_name_from_mail`
](https://github.com/helpyio/helpy_imap/blob/master/lib/imap_processor.rb#L148)method, called from `create_user_from_email` 
(in fact it was only happening when there was no user  in the db associated with the mail of the sender).

I forced the creation of the user using just the email and this error was fixed.
changed [line 158](https://github.com/helpyio/helpy_imap/blob/master/lib/imap_processor.rb#L158) with
```
@user.name = get_name_from_mail.blank? ? get_email_from_mail.gsub(/[^a-zA-Z]/, '') : get_name_from_mail 
```

Later I encountered a similar error processing the email body,
fixed adding `return entity unless entity.respond_to?('encoding')` inside the encode_entity method.

**Comment by scott** [comment]
@benoitgoyette that seems to be a leftover from the code used with the Griddler gem, which does pass a hash. I will fix this and post an update in a couple days.

@fracalo thanks for that, I will take a look at the same time as this hash/string array mixup.
